### ISSUE TITLE
Add Support for AppleWatch

### ISSUE THREAD

**Issue by magaHH** [worthbak/apple-store-inventory-checker#10]
Is it possible to add support for the AppleWatch (Ultra)?

Thx!

**Comment by worthbak** [comment]
It is possible to use the script to search for the Ultra, but there's some assembly required: you'll need to modify [this function](https://github.com/worthbak/apple-store-inventory-checker/blob/main/index.js#L12) to include the relevant Apple Watch Ultra SKUs (that you can find elsewhere online). After that, the script should be able to search for whatever SKUs you input.

If you're looking for a more out-of-the-box solution, I'll point you to [InventoryWatch](https://worthbak.github.io/inventory-checker-app/), a native macOS app that can run searches like this for you. I'll be adding support for Apple Watch Ultra soon.
