### ISSUE TITLE
R118 Birmingham doesn't work

### ISSUE THREAD

**Issue by ensignvorik** [worthbak/apple-store-inventory-checker#8]
This I assume is the ID for the Birmingham New Street UK based store, but always gives me an error.

It's missing from the ID list (I tried adding it manually but no dice)

Is listed in the by City list, but I'm not sure if it's even the right store. Always throws an error. I can see some stock by doing the code for the next nearest store (R255 Solihull)

**Comment by worthbak** [comment]
This appears to be an error within Apple's fulfillment API, and not an issue with the script itself. If you query the API for a MacBook Pro model and use store `R118`, like this: 

```
https://www.apple.com/uk/shop/fulfillment-messages?parts.0=MKGR3B/A&searchNearby=true&store=R118
```

the API will return a parsable response, but with an error message field noting:

```
"errorMessage": "Invalid postcode."
```

Indeed, if you take the postal code Apple uses for the Birmingham store, `B2 4DB`, and input it into Apple's website when searching for available stock, this is what you'll see: 

<img width="600" alt="Screen Shot 2022-01-07 at 6 40 14 AM" src="https://user-images.githubusercontent.com/10028428/148552341-5c39ec03-7196-486a-8897-48ad018727c3.png">

Caveat that I know nothing about UK postal codes 🙃 in any case, this appears to be either an issue with Apple's fulfillment API, or an issue with their Birmingham store data, neither of which I'm able to address with this script. 

Any thoughts or suggestions, @ensignvorik?

**Comment by ensignvorik** [comment]
Only suggestion from me I guess is to report the problem to Apple if it's a problem with their API.

I'll leave that up to you guys. My workaround of using the Solihull store was sufficient in being able to find stock when 1 became available (massive shortage still here in the UK) so thank you for this script.

**Comment by worthbak** [comment]
Eh, this API is undocumented and externally unsupported by Apple - tbh I'm surprised it's available for external use at all without some encryption key. The API, and therefore this script, is at the mercy of Apple and any bugs they have or decide to fix ¯\_(ツ)_/¯ good to see you have a decent workaround though!
